---
title: "Monus_GRaMPS"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Initial Set Up

```{r}
library(tidyverse)
library(here)
library(bestNormalize)
```

## ANPP

### Calculations

```{r}
# load in 2018 ANPP data
ANPP_df <- read_csv(here("data","ANPP.csv"), show_col_types = FALSE)

# Change treatment names to align with Monus data sets
ANPP_df <- ANPP_df |>
    mutate(
    Treatment = as.factor(Treatment) |> 
      recode_factor(C = "Ctrl", D = "Exl", W = "Add"))

# calculate canopy cover for each Observation 
# From Seth "To calculate total vegetation cover per quadrat, multiply the canopy cover value by the count, then sum all these products for every species in the quadrat....It sounds like Brittney used plot as a level of replication, so could take average of the 2 quadrats in each plot. "
ANPP_df <- ANPP_df |>
    mutate(
    Canopy_coverXcount = Canopy_cover * Count)

# sum Canopy_coverXcount and ANPP for each species within individual quadrats
# note that per HT's conversation (2024-03-27) with SM, ANPP already has 'count' taken into account, no need to multiple it
ANPP_by_spp_by_quadrat <- ANPP_df |>
  group_by(Site, Treatment, Plot, Quadrat, Species) |>
  summarize(
    CanopyCoverBySpp = sum(Canopy_coverXcount, na.rm=TRUE),
    ANPPBySpp = sum(NPP_g_m2, na.rm=TRUE)) 

# sum canopy cover and ANPP data for all species within each quadrat
ANPP_by_quadrat <- ANPP_by_spp_by_quadrat |>
  group_by(Site, Treatment, Plot, Quadrat) |>
  summarize(
    QuadCanopyCover = sum(CanopyCoverBySpp, na.rm=TRUE),
    QuadANPP = sum(ANPPBySpp, na.rm=TRUE)) 

# reduce cover and ANPP data to means for each plot
ANPP_by_plot <- ANPP_by_quadrat |>
  group_by(Site, Treatment, Plot) |>
  summarize(
    plot_mean_Cover = mean(QuadCanopyCover, na.rm=TRUE),
    plot_mean_ANPP = mean(QuadANPP, na.rm=TRUE),
    n_quadrats    = n())

# reduce ANPP and cover data to means for site x treatment combination
ANPP_by_trt <- ANPP_by_plot |>
  group_by(Site, Treatment) |>
  summarize(
    n_plots = n(),
    mean_ANPP = mean(plot_mean_ANPP, na.rm=TRUE),
    sd_ANPP = sd(plot_mean_ANPP),
    se_ANPP = sd_ANPP/sqrt(n_plots),
    mean_Cover = mean(plot_mean_Cover, na.rm=TRUE),
    sd_Cover = sd(plot_mean_Cover),
    se_Cover = sd_Cover/sqrt(n_plots)
    )

# quick plot to look at mass versus cover
plot(x = ANPP_by_trt$mean_ANPP, y = ANPP_by_trt$mean_Cover)
```

## Root Biomass (g m-2)

### Calculations

```{r}
# load in root biomass data
root_biomass_df <- read_csv(here("data","RootBiomass.csv"), show_col_types = FALSE)

# Convert from long to wide format for root core depth
root_biomass_wide_df <- root_biomass_df |>
  pivot_wider(names_from = Depth, values_from = Root_mass,
              names_prefix = "Root_mass_")

# do a second pivot wider to separate out the two microsites
root_biomass_wide_df <- root_biomass_wide_df |>
  pivot_wider(names_from = Microsite, values_from = c(Root_mass_upper,
                                                      Root_mass_lower),
              names_sep = "_")

# Add core depths together 
# Calculate roots biomass in units of g m-2, based on the 7 cm diameter corer
root_biomass_wide_df <- root_biomass_wide_df |>
    mutate(
    Root_mass_Can = Root_mass_upper_Can + Root_mass_lower_Can,
    Root_mass_IC = Root_mass_upper_IC + Root_mass_lower_IC,
    Root_mass_Can_gm2 = Root_mass_Can /((3.14159*3.5^2)/(100*100)),
    Root_mass_IC_gm2 = Root_mass_IC / ((3.14159*3.5^2)/(100*100))
    )

```

### 

## Combined ANPP and Root Biomass

```{r}
# group by depth and canopy
ANPPandRoot_df <- left_join(ANPP_by_plot, root_biomass_wide_df, by = c("Site", "Treatment", "Plot"))

# calculate area-weighted root biomass
ANPPandRoot_df <- ANPPandRoot_df |>
    mutate(
    Root_mass_Can_gm2_weighted = Root_mass_Can_gm2 * plot_mean_Cover/100,
    Root_mass_IC_gm2_weighted = Root_mass_IC_gm2 * (1-plot_mean_Cover/100),
    Root_mass_total_gm2 = Root_mass_Can_gm2_weighted + Root_mass_IC_gm2_weighted,
    root_to_ANPP = Root_mass_total_gm2/plot_mean_ANPP
    )

# quick plot to look at mass versus cover
plot(x = ANPPandRoot_df$Root_mass_total_gm2, y = ANPPandRoot_df$plot_mean_ANPP)

# reduce ANPP and root biomass to means for site x treatment combination
ANPP_roots_by_trt <- ANPPandRoot_df |>
  group_by(Site, Treatment) |>
  summarize(
    n_plots = sum(!is.na(plot_mean_ANPP)),
    mean_ANPP = mean(plot_mean_ANPP, na.rm=TRUE),
    sd_ANPP = sd(plot_mean_ANPP, na.rm=TRUE),
    se_ANPP = sd_ANPP/sqrt(n_plots),
    n_roots = sum(!is.na(Root_mass_total_gm2)),
    mean_Root_gm2 = mean(Root_mass_total_gm2, na.rm=TRUE),
    sd_Root_gm2 = sd(Root_mass_total_gm2, na.rm=TRUE),
    se_Root_gm2 = sd_Root_gm2/sqrt(n_roots)
    )

```

### Plots - ANPP and root biomass by treatment and site

```{r}
#|label: column-graph-ANPP-by-trt-and-site

# ANPP Plots 
ANPPandRoot_df <- ANPPandRoot_df |>
  mutate(
    SiteOrder = factor(Site, levels=c("BP","ANT","BC","ARB","CC"), 
                     labels=c("Desert Scrub","Desert Grassland","Juniper Savanna",
                              "Ponderosa Pine Meadow","Mixed Conifer Meadow")),
    TreatmentOrder = factor(Treatment, levels=c("Exl","Ctrl","Add"), 
                        labels=c("Exclusion","Ambient","Addition")) 
  )

ANPP <- ANPPandRoot_df |>
  ggplot(aes(x = SiteOrder, y = plot_mean_ANPP, fill = TreatmentOrder)) + 
  geom_boxplot(position = position_dodge(0.8)) +  
  scale_fill_manual(name = "Treatment", values = c("#de2d26", "#bdbdbd", "#08519c")) +
#  scale_y_continuous(limits = c(0, 6), breaks = c(0, 2, 4, 6)) +
  labs(x = "Site", 
       y = "Mean Plot ANPP (g m-2)") +  # need to double check Seth's units
  theme_grey(base_size = 18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.3, 0.7),
    panel.background = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
  ) 
ggsave(here("figures", "ANPP.png"), plot = ANPP, width = 10, height = 8)
```

```{r}
#|label: column-graph-rootbiomass-by-trt-and-site

roots_total_gm2 <- ANPPandRoot_df |>
  ggplot(aes(x = SiteOrder, y = Root_mass_total_gm2, fill = TreatmentOrder)) + 
  geom_boxplot(position = position_dodge(0.8)) +  
  scale_fill_manual(name = "Treatment", values = c("#de2d26", "#bdbdbd", "#08519c")) +
#  scale_y_continuous(limits = c(0, 6), breaks = c(0, 2, 4, 6)) +
  labs(x = "Site", 
       y = "Root Mass (g m-2)") +  
  theme_grey(base_size = 18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.3, 0.7),
    panel.background = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
  ) 
ggsave(here("figures", "roots_total_gm2.png"), plot = roots_total_gm2, width = 10, height = 8)

roots_Can_gm2 <- ANPPandRoot_df |>
  ggplot(aes(x = SiteOrder, y = Root_mass_Can_gm2, fill = TreatmentOrder)) + 
  geom_boxplot(position = position_dodge(0.8)) +  
  scale_fill_manual(name = "Treatment", values = c("#de2d26", "#bdbdbd", "#08519c")) +
#  scale_y_continuous(limits = c(0, 6), breaks = c(0, 2, 4, 6)) +
  labs(x = "Site", 
       y = "Root Mass in Canopy microsites (g m-2)") +  
  theme_grey(base_size = 18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.3, 0.7),
    panel.background = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
  ) 
ggsave(here("figures", "roots_Can_gm2.png"), plot = roots_Can_gm2, width = 10, height = 8)

roots_IC_gm2 <- ANPPandRoot_df |>
  ggplot(aes(x = SiteOrder, y = Root_mass_IC_gm2, fill = TreatmentOrder)) + 
  geom_boxplot(position = position_dodge(0.8)) +  
  scale_fill_manual(name = "Treatment", values = c("#de2d26", "#bdbdbd", "#08519c")) +
#  scale_y_continuous(limits = c(0, 6), breaks = c(0, 2, 4, 6)) +
  labs(x = "Site", 
       y = "Root Mass in IC microsites (g m-2)") +  
  theme_grey(base_size = 18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.3, 0.7),
    panel.background = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
  ) 
ggsave(here("figures", "roots_IC_gm2.png"), plot = roots_IC_gm2, width = 10, height = 8)
```

```{r}
#|label: column-graph-ANPP-to-rootbiomass-by-trt-and-site

root_shoot_plot <- ANPPandRoot_df |>
  ggplot(aes(x = SiteOrder, y = root_to_ANPP, fill = TreatmentOrder)) + 
  geom_boxplot(position = position_dodge(0.8)) +  
  scale_fill_manual(name = "Treatment", values = c("#de2d26", "#bdbdbd", "#08519c")) +
#  scale_y_continuous(limits = c(0, 6), breaks = c(0, 2, 4, 6)) +
  labs(x = "Site", 
       y = "Root Mass:ANPP") +  
  theme_grey(base_size = 18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.3, 0.7),
    panel.background = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
  ) 
ggsave(here("figures", "root_to_ANPP.png"), plot = root_shoot_plot, width = 10, height = 8)
```

## ANOVAs

### Root biomass - Canopy (g m-2)

```{r}
# check normality and transform as needed
qqnorm(ANPPandRoot_df$Root_mass_Can_gm2) 
shapiro.test(ANPPandRoot_df$Root_mass_Can_gm2) # P < 0.05 - reject hypothesis of normality
BN_RootCan_gm2 <- bestNormalize(ANPPandRoot_df$Root_mass_Can_gm2)
BN_RootCan_gm2 # show options for normalizing
ANPPandRoot_df$Root_mass_Can_gm2_norm <- predict(BN_RootCan_gm2)
qqnorm(ANPPandRoot_df$Root_mass_Can_gm2_norm) # way better
qqline(ANPPandRoot_df$Root_mass_Can_gm2_norm) # add line to plot
shapiro.test(ANPPandRoot_df$Root_mass_Can_gm2_norm) # P > 0.05 - looks good!

# 2-way ANOVA model with transformed data
Root_Can_gm2_anova <- aov(Root_mass_Can_gm2_norm ~ 
                            Site * Treatment, data=ANPPandRoot_df)
summary(Root_Can_gm2_anova)
## No significant treatment differences
```

### Root biomass - Intercanopy

```{r}
# check normality and transform as needed
qqnorm(ANPPandRoot_df$Root_mass_IC_gm2) 
shapiro.test(ANPPandRoot_df$Root_mass_IC_gm2) # P < 0.05 - reject hypothesis of normality
BN_RootIC_gm2 <- bestNormalize(ANPPandRoot_df$Root_mass_IC_gm2)
BN_RootIC_gm2 # show options for normalizing
ANPPandRoot_df$Root_mass_IC_gm2_norm <- predict(BN_RootIC_gm2)
qqnorm(ANPPandRoot_df$Root_mass_IC_gm2_norm) # way better
qqline(ANPPandRoot_df$Root_mass_IC_gm2_norm) # add line to plot
shapiro.test(ANPPandRoot_df$Root_mass_IC_gm2_norm) # P > 0.05 - looks good!

# 2-way ANOVA model with transformed data
Root_IC_gm2_anova <- aov(Root_mass_IC_gm2_norm ~ 
                            Site * Treatment, data=ANPPandRoot_df)
summary(Root_IC_gm2_anova)
## Significant Site and Treatment differences (no interaction)

# Perform pairwise comparisons using Tukey's HSD test
IC_pairwise <- TukeyHSD(Root_IC_gm2_anova)
print(IC_pairwise)
plot(IC_pairwise)
```

### Root biomass - Combined IC and Canopy 

using area-weighted values for whole plot root mass (g m-2)

```{r}
# check normality and transform as needed
qqnorm(ANPPandRoot_df$Root_mass_total_gm2) 
shapiro.test(ANPPandRoot_df$Root_mass_total_gm2) # P < 0.05 - reject hypothesis of normality
BN_Root_mass_total_gm2 <- bestNormalize(ANPPandRoot_df$Root_mass_total_gm2)
BN_Root_mass_total_gm2 # show options for normalizing
ANPPandRoot_df$Root_mass_total_gm2_norm <- predict(BN_Root_mass_total_gm2)
qqnorm(ANPPandRoot_df$Root_mass_total_gm2_norm) # way better
qqline(ANPPandRoot_df$Root_mass_total_gm2_norm) # add line to plot
shapiro.test(ANPPandRoot_df$Root_mass_total_gm2_norm) # still not normally, but improved

# 2-way ANOVA model with transformed data
Root_total_gm2_anova <- aov(Root_mass_total_gm2_norm ~ 
                            Site * Treatment, data=ANPPandRoot_df)
summary(Root_total_gm2_anova)
## Significant Site and Treatment differences (no interaction)

# Perform pairwise comparisons using Tukey's HSD test
total_pairwise <- TukeyHSD(Root_total_gm2_anova)
print(total_pairwise)
plot(total_pairwise)
```

### ANPP

```{r}
# check normality and transform as needed
qqnorm(ANPP_by_plot$plot_mean_ANPP) 
shapiro.test(ANPP_by_plot$plot_mean_ANPP) # P < 0.05 - reject hypothesis of normality
BN_ANPP <- bestNormalize(ANPP_by_plot$plot_mean_ANPP)
BN_ANPP # show options for normalizing
ANPP_by_plot$plot_mean_ANPP_norm <- predict(BN_ANPP)
qqnorm(ANPP_by_plot$plot_mean_ANPP_norm) # a little better
qqline(ANPP_by_plot$plot_mean_ANPP_norm) # add line to plot
shapiro.test(ANPP_by_plot$plot_mean_ANPP_norm) # P > 0.05 - ok

# 2-way ANOVA model with transformed data
ANPP_anova <- aov(plot_mean_ANPP_norm ~ Site * Treatment, data=ANPP_by_plot)
summary(ANPP_anova)

# Perform pairwise comparisons using Tukey's HSD test
ANPP_pairwise <- TukeyHSD(ANPP_anova)
print(ANPP_pairwise)
plot(ANPP_pairwise)

```

## 

Area-weighted root biomass

Root-to-ANPP
